### ISSUE TITLE
[Bug] The main Steam window doesn't change color

### ISSUE THREAD

**Issue by elifian** [shdwmtr/millennium#201]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

The main Steam window doesn't change color, while all other windows (friends, settings, even the store) do.

### Expected Behavior

Everything should change color.

### Steps To Reproduce

Install the theme, it works, restart, and it no longer works.

### Operating System

Windows

### Anything else?

![image](https://github.com/user-attachments/assets/69374807-51e5-4245-a363-72f5fad8d2d3)

```log
[58:17.165] INFO Millennium@v2.17.2 is up to date.
[58:17.167] INFO Ports: { FTP: 4156, IPC: 4174 }
[58:17.167] INFO Plugins: { core: Enabled }
[58:17.167] INFO Verifying Python environment...
[58:17.201] INFO Starting plugin backends...
[58:17.201] INFO Opting to use '8080' for SteamDBG port
[58:17.201] INFO Created thread 3936307252 for plugin 'pipx'
[58:17.202] INFO Starting frontend socket...
[58:17.202] INFO Startup took 773 ms
[58:17.214] INFO Redirecting stdout/stderr for plugin 'pipx'
[58:17.214] INFO Invoking plugin main callback for 'pipx'
[58:17.214] INFO Started preloader module
[58:17.338] PIPX Starting Package Manager...
[58:17.347] PIPX checking for packages on Windows
[58:17.361] PIPX All required packages are satisfied.
[58:17.361] PIPX Finished in 21.82 ms
[58:17.361] INFO Preloader finished...
[58:17.361] INFO Notified plugin [pipx] to shut down...
[58:17.361] INFO Orphaned 'pipx', jumping off the mutex lock...
[58:17.361] INFO Trying to join thread 3936307252...
[58:17.361] INFO Shutting down plugin 'pipx'
[58:17.367] INFO Ended sub-interpreter...
[58:17.367] INFO Shut down plugin 'pipx'
[58:17.367] INFO Successfully joined thread
[58:17.368] INFO Successfully unloaded pipx
[58:17.368] INFO Enabled Plugins: 1, Loaded Plugins : 0
[58:17.368] INFO Starting backends...
[58:17.369] INFO Ports: { FTP: 4156, IPC: 4177 }
[58:17.369] INFO Plugins: { core: Enabled }
[58:17.369] INFO Plugins: { core: Enabled }
[58:17.370] INFO Starting backend for 'core'
[58:17.370] INFO Created thread 1046302796 for plugin 'core'
[58:17.380] INFO Redirecting stdout/stderr for plugin 'core'
[58:17.380] INFO Invoking plugin main callback for 'core'
[58:17.408] CORE Loading Millennium-Core@v2.17.2
[58:17.896] CORE Starting the websocket for theme installer...
[58:17.897] CORE Ready in 506.052 milliseconds!
[58:17.897] INFO Successfully loaded 'core'
[58:17.898] INFO Enabled Plugins: 1, Loaded Plugins : 1
[58:17.898] INFO Finished preparing backends...
[58:17.910] CORE Server started on ws://localhost:9123
[58:18.411] INFO Connected to Steam @ 0xd19f2f0
[58:18.412] INFO Connected to SharedJSContext in 0 ms
[58:18.412] INFO Preparing to inject frontend shims...
[58:18.941] INFO Successfully sent debugger pause...
[58:19.510] INFO Debugger has paused!
[58:19.510] INFO Ready to inject shims!
[58:19.511] INFO Registering for load event @ 0xf5cfd50
[58:19.512] INFO Enabled Plugins: 1, Loaded Plugins : 1
[58:19.512] INFO Finished preparing backends...
[58:19.512] INFO Invoking & removing on load event @ 0x6378140
[58:19.513] INFO Notifying frontend of backend load...
[58:19.628] INFO Successfully resumed debugger, injecting shims...
[58:19.630] INFO Successfully injected shims, updating state...
[58:19.630] INFO Successfully notified frontend...
[58:19.630] INFO Frontend notifier finished!
[58:21.221] CORE Using default accent color
[58:21.230] CORE SteamUI successfully loaded!
[58:26.319] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[58:26.320] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[58:26.328] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[58:47.426] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[59:08.194] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[59:08.195] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[59:08.200] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[59:09.665] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[59:10.312] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[59:10.518] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
  ```
  The WARN (Steam-Error) appears when opening the "Themes" button and working with it.
  I tried different versions of the Millennium theme, but it doesn't work. At best, it only worked until the first restart. And I also tried deleting everything except steam.exe/steamapps/userdata/config and reinstalling Millennium from scratch.

**Comment by elifian** [comment]
Right now, I restarted, and it works for one restart.
![image](https://github.com/user-attachments/assets/25130934-ac67-45f4-a7f4-d8fbd4c729fe)
```log
[18:46.729] INFO Millennium@v2.17.2 is up to date.
[18:46.730] INFO Ports: { FTP: 4699, IPC: 4721 }
[18:46.731] INFO Plugins: { core: Enabled }
[18:46.731] INFO Verifying Python environment...
[18:46.765] INFO Starting plugin backends...
[18:46.765] INFO Opting to use '8080' for SteamDBG port
[18:46.765] INFO Created thread 3936307252 for plugin 'pipx'
[18:46.766] INFO Starting frontend socket...
[18:46.766] INFO Startup took 994 ms
[18:46.775] INFO Redirecting stdout/stderr for plugin 'pipx'
[18:46.775] INFO Invoking plugin main callback for 'pipx'
[18:46.775] INFO Started preloader module
[18:46.892] PIPX Starting Package Manager...
[18:46.901] PIPX checking for packages on Windows
[18:46.915] PIPX All required packages are satisfied.
[18:46.915] PIPX Finished in 21.90 ms
[18:46.915] INFO Preloader finished...
[18:46.915] INFO Notified plugin [pipx] to shut down...
[18:46.915] INFO Orphaned 'pipx', jumping off the mutex lock...
[18:46.915] INFO Trying to join thread 3936307252...
[18:46.915] INFO Shutting down plugin 'pipx'
[18:46.920] INFO Ended sub-interpreter...
[18:46.920] INFO Shut down plugin 'pipx'
[18:46.920] INFO Successfully joined thread
[18:46.920] INFO Successfully unloaded pipx
[18:46.920] INFO Enabled Plugins: 1, Loaded Plugins : 0
[18:46.921] INFO Starting backends...
[18:46.922] INFO Ports: { FTP: 4699, IPC: 4726 }
[18:46.922] INFO Plugins: { core: Enabled }
[18:46.922] INFO Plugins: { core: Enabled }
[18:46.922] INFO Starting backend for 'core'
[18:46.922] INFO Created thread 1046302796 for plugin 'core'
[18:46.932] INFO Redirecting stdout/stderr for plugin 'core'
[18:46.932] INFO Invoking plugin main callback for 'core'
[18:46.955] CORE Loading Millennium-Core@v2.17.2
[18:47.398] CORE Starting the websocket for theme installer...
[18:47.399] CORE Ready in 457.682 milliseconds!
[18:47.399] INFO Successfully loaded 'core'
[18:47.399] INFO Enabled Plugins: 1, Loaded Plugins : 1
[18:47.399] INFO Finished preparing backends...
[18:47.415] CORE Server started on ws://localhost:9123
[18:48.008] INFO Connected to Steam @ 0xd1af2f0
[18:48.008] INFO Connected to SharedJSContext in 0 ms
[18:48.008] INFO Preparing to inject frontend shims...
[18:48.537] INFO Successfully sent debugger pause...
[18:49.466] INFO Debugger has paused!
[18:49.466] INFO Ready to inject shims!
[18:49.467] INFO Registering for load event @ 0xf5efd50
[18:49.468] INFO Enabled Plugins: 1, Loaded Plugins : 1
[18:49.468] INFO Finished preparing backends...
[18:49.468] INFO Invoking & removing on load event @ 0x648b058
[18:49.469] INFO Notifying frontend of backend load...
[18:49.575] INFO Successfully resumed debugger, injecting shims...
[18:49.577] INFO Successfully injected shims, updating state...
[18:49.577] INFO Successfully notified frontend...
[18:49.577] INFO Frontend notifier finished!
[18:51.061] CORE Using default accent color
[18:51.070] CORE SteamUI successfully loaded!
[18:57.207] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[18:57.208] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
[18:57.219] WARN (Steam-Error) Trying to use ConfigContext without a provider!  Add ConfigContextRoot to application.
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=896d8da72bde512a34f8:1:4098600)
  ```

**Comment by elifian** [comment]
One more thing. If you open the "Themes" tab, and then any other steam tab
![image](https://github.com/user-attachments/assets/bc327c21-2ce8-4fae-9851-07a298fe9396)
![image](https://github.com/user-attachments/assets/ab326497-15d2-4842-bb7d-f142228600f7)

**Comment by shdwmtr** [comment]
So it still doesn't entirely work?

**Comment by madmaxgrey** [comment]
that warn (steam-error) can be ignored as you see at the end it says non-fatel. thats just a normal thing steam does. even without millennium you would see those errors

**Comment by elifian** [comment]
> So it still doesn't entirely work?

yeah, still not working properly

**Comment by elifian** [comment]
There is such a problem.  Maybe it will give you an idea of how to fix the error as a whole...
![Image](https://github.com/user-attachments/assets/971a518a-c3c9-4f82-905d-d500226cf58e)

**Comment by madmaxgrey** [comment]
> There is such a problem. Maybe it will give you an idea of how to fix the error as a whole... ![Image](https://github.com/user-attachments/assets/971a518a-c3c9-4f82-905d-d500226cf58e)

we are already aware of that, we already have a fix for it in the next update.

**Comment by madmaxgrey** [comment]
there will be a new millennium update within the next week or so were changing how you access millennium it will have its own window instead of being in steam > settings

**Comment by madmaxgrey** [comment]
![Image](https://github.com/user-attachments/assets/3ef89990-e9f9-42aa-9cf4-53cd3183ea80)

![Image](https://github.com/user-attachments/assets/aad29228-7519-457a-9d04-9ab870eaf081)
heres a preview of where it will be accessed from in the upcoming update

**Comment by shdwmtr** [comment]
Fixed in latest pre-release. Full release should follow soon.

**Comment by elifian** [comment]
Hello, everything is still not working properly for some reason.

![Image](https://github.com/user-attachments/assets/0da17a07-2349-4daa-a58d-cfcc40a529d1)

[millennium.txt](https://github.com/user-attachments/files/19394785/millennium.txt)
[package_manager.txt](https://github.com/user-attachments/files/19394784/package_manager.txt)
[standard_output.txt](https://github.com/user-attachments/files/19394786/standard_output.txt)

**Comment by shdwmtr** [comment]
Does this consistently happen even across restarts / theme changes?

**Comment by elifian** [comment]
> Does this consistently happen even across restarts / theme changes?

Yes, this is the original on a permanent basis. In general, the main interface is not repainted...

**Comment by shdwmtr** [comment]
Does it work if you don't use small mode?
